# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
np.show_config()

1.13.3
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rockroku/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rockroku/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rockroku/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rockroku/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rockroku/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rockroku/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rockroku/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rockroku/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Use

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
zero_3 = np.zeros(10)
zero_3

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
print(zero_3.size)
print(zero_3.itemsize)


10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
temp6 = np.zeros(10)
temp6[4] = 1
temp6

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
temp7 = np.arange(10, 49)

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
temp7[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
temp9 = np.arange(0, 9)
temp9.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
temp10 = np.array([1,2,0,0,4,0])
np.nonzero(temp10)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
np.random.random((3, 3, 3))

array([[[ 0.55021481,  0.89088803,  0.90084491],
        [ 0.46636364,  0.601487  ,  0.77025523],
        [ 0.3700643 ,  0.81290731,  0.45036061]],

       [[ 0.8891436 ,  0.50986901,  0.98099612],
        [ 0.77470041,  0.92166179,  0.21926133],
        [ 0.18240685,  0.61303888,  0.93481695]],

       [[ 0.99877774,  0.33637061,  0.11322667],
        [ 0.18718673,  0.39199743,  0.5133014 ],
        [ 0.46986045,  0.09842172,  0.49261103]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
temp13 = np.random.random((10, 10))
print(temp13)
print("min:", np.min(temp13))
print("max:", np.max(temp13))

[[  5.92717876e-01   9.23930308e-01   2.39062805e-01   4.96335420e-01
    9.69778519e-01   5.69598060e-02   2.12783285e-01   4.33222985e-01
    7.35658475e-01   6.35155443e-01]
 [  9.80205421e-01   6.33171252e-01   1.85764958e-01   6.58965919e-02
    6.86814172e-01   8.88248027e-01   4.06842334e-01   5.67857245e-01
    5.57593081e-03   4.78666499e-01]
 [  2.89429402e-01   9.21436609e-01   9.22302672e-04   1.61882270e-01
    3.81963078e-01   9.46320130e-01   9.91081659e-01   4.26315911e-01
    6.57404914e-01   5.01022897e-01]
 [  2.30888286e-01   8.83603533e-01   5.40624541e-01   8.92549551e-02
    3.55981576e-02   8.59743328e-01   5.46376492e-01   4.74091145e-01
    6.07364134e-01   9.78089369e-01]
 [  3.35946033e-01   3.43100962e-01   2.76849222e-01   9.66239625e-01
    4.26141647e-01   2.85342653e-01   4.95476644e-01   5.51431871e-01
    9.00012842e-01   7.83869777e-01]
 [  1.34626296e-01   2.37977200e-01   6.74962961e-01   9.13968107e-02
    5.65250259e-01   5.16282936e-01   4.81679

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
temp14 = np.random.random((30))
print(temp14)
print("mean:", np.mean(temp14))

[ 0.81641584  0.87007552  0.55076635  0.48917815  0.13626261  0.10073058
  0.96242025  0.12286683  0.88062668  0.04313443  0.37339314  0.60270723
  0.22854811  0.97224272  0.4299207   0.56321528  0.00113991  0.56431651
  0.45504336  0.7281396   0.229025    0.91266651  0.78410441  0.08514186
  0.11837416  0.91528091  0.5113605   0.65258232  0.38868185  0.36460485]
mean: 0.495098871927


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
temp15 = np.ones((5, 5))
temp15[1:-1, 1:-1] = 0
temp15

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
temp16 = np.ones((5, 5))
print(temp16)
print(np.pad(temp16, 1, mode='constant'))

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
False
nan
False


In [18]:
3*0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [19]:
temp18 = np.diag([1,2,3,4], k=-1)
print(temp18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [20]:
temp19 = np.zeros((8,8))
print(temp19, end="\n\n")
temp19[1::2,::2] = 1
print(temp19, end="\n\n")
temp19[::2,1::2] = 1
print(temp19)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [21]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [22]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [23]:
temp22 = np.random.random((5,5)) * 100
print(temp22)
temp22_min = temp22.min()
temp22_max = temp22.max()
temp22_normal = (temp22-temp22_min) / (temp22_max-temp22_min)
temp22_normal

[[ 22.65878364  85.33192642  83.97860859  29.81737232  63.81336458]
 [ 43.65390993  93.000016    79.47972633  92.04397654  15.03167997]
 [ 11.24199646  72.26268079  12.23660073  23.90645421  86.78138814]
 [  1.61517281  60.33226506  49.91510975  81.34882584  41.35492794]
 [ 46.52065327  99.09802666  42.40846627  59.31995062  59.98692747]]


array([[ 0.21586987,  0.85878439,  0.84490177,  0.2893042 ,  0.63804238],
       [ 0.43124237,  0.9374453 ,  0.79875127,  0.92763804,  0.1376294 ],
       [ 0.09875402,  0.72471727,  0.10895688,  0.22866874,  0.87365328],
       [ 0.        ,  0.60233251,  0.4954711 ,  0.8179249 ,  0.40765892],
       [ 0.46065004,  1.        ,  0.41846634,  0.59194797,  0.59878997]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [24]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [25]:
temp24_1 = np.random.random((5, 3)) * 10
print(temp24_1, end="\n\n")
temp24_2 = np.random.random((3, 2)) * 10
print(temp24_2, end="\n\n")
temp24_3 = np.dot(temp24_1, temp24_2)
print(temp24_3, end="\n\n")


[[ 1.82002818  3.64507429  9.514277  ]
 [ 6.18251504  6.98134569  5.59448607]
 [ 0.29101952  0.89491347  3.29497181]
 [ 8.11496275  0.99830333  5.14808526]
 [ 4.72149762  5.47014979  3.76870037]]

[[ 6.22639388  3.90665677]
 [ 2.64574147  7.59111886]
 [ 5.77727501  3.6648928 ]]

[[ 75.9427313   69.6492229 ]
 [ 89.28649412  97.65238087]
 [ 23.21567012  20.00602632]
 [ 82.91011119  58.14779393]
 [ 65.64332447  73.78171072]]



#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [26]:
temp25 = np.arange(3, 9)
temp25[(3 < temp25) & (temp25 <= 8)] *= -1
temp25

array([ 3, -4, -5, -6, -7, -8])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = arange(8)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9223372036854775808]
[ -9.22337204e+18]


/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  from ipykernel import kernelapp as app


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [30]:
temp29 = np.random.uniform(-10,+10,10)
print(temp29, end="\n\n")
temp29 = np.copysign(np.floor(np.abs(temp29)), temp29)
print(temp29)

[-8.4408466  -1.36278333  6.5126529   2.35438246 -7.55341229  2.00990986
 -7.54135693 -7.9404558  -7.9637111  -6.03770529]

[-8. -1.  6.  2. -7.  2. -7. -7. -7. -6.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [31]:
temp30_1 = np.arange(1, 5)
temp30_2 = np.arange(3, 6)

In [32]:
%time
print(np.intersect1d(temp30_1, temp30_2))

CPU times: user 5 µs, sys: 1e+03 ns, total: 6 µs
Wall time: 13.1 µs
[3 4]


In [33]:
%time
print(set(temp30_1) & set(temp30_2))

CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 12.2 µs
{3, 4}


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [34]:
np.int16(32000) * np.int16(3)

/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: overflow encountered in short_scalars
  if __name__ == '__main__':


30464

In [35]:
default_setting = np.seterr()
default_setting

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [36]:
old_settings = np.seterr(all='ignore')
old_settings

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [37]:
np.int16(32000) * np.int16(3)

30464

In [38]:
old_settings = np.seterr(**default_setting)  #seterr to known value
np.int16(32000) * np.int16(3)

/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in short_scalars
  from ipykernel import kernelapp as app


30464

In [39]:
with np.errstate(over='ignore'):
    np.int16(32000) * np.int16(3)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [40]:
print("np.sqrt(-1):", np.sqrt(-1))
print("np.emath.sqrt(-1):", np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

np.sqrt(-1): nan
np.emath.sqrt(-1): 1j


/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':
/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:3: RuntimeWarning: invalid value encountered in sqrt
  app.launch_new_instance()


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [41]:
today     = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow  = today + np.timedelta64(1, 'D')
print("today:", today)
print("yesterday:", yesterday)
print("tomorrow:", tomorrow)

today: 2018-09-18
yesterday: 2018-09-17
tomorrow: 2018-09-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [42]:
np.arange(np.datetime64('2018-07-01', 'D'), np.datetime64('2018-08-01', 'D'))

array(['2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04',
       '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08',
       '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12',
       '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16',
       '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20',
       '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24',
       '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28',
       '2018-07-29', '2018-07-30', '2018-07-31'], dtype='datetime64[D]')

In [43]:
np.arange(np.datetime64('2018-07-01', 'D'), np.datetime64('2018-07-31', 'D') + 1)

array(['2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04',
       '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08',
       '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12',
       '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16',
       '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20',
       '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24',
       '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28',
       '2018-07-29', '2018-07-30', '2018-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [44]:
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
np.add(A, B, out=B)
np.divide(-A, 2, out=A)
np.multiply(A, B)

array([[-0.09860005, -0.44922925],
       [-0.38930823, -0.02406514]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [45]:
temp_rand_36 = np.random.rand(3) * 10
print("temp_rand_36:", temp_rand_36)
print(np.floor(temp_rand_36))
print(np.ceil(temp_rand_36))
print(temp_rand_36.astype(np.int32))
print(np.trunc(temp_rand_36))
print(temp_rand_36 - temp_rand_36 % 1)

temp_rand_36: [ 6.76603186  3.5630295   8.58862092]
[ 6.  3.  8.]
[ 7.  4.  9.]
[6 3 8]
[ 6.  3.  8.]
[ 6.  3.  8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [46]:
np.zeros((5, 5)) + np.arange(0, 5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [47]:
def get_10_num():
    for i in range(10):
        yield i
np.fromiter(get_10_num(), int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [48]:
np.linspace(0, 1, num=11, endpoint=False)[1:]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [49]:
temp40 = np.random.rand(10)
print("temp40:", temp40)
print("temp40 sorted:", np.sort(temp40))

temp40: [ 0.04484579  0.04655535  0.55113998  0.3611967   0.31972742  0.29597089
  0.39546552  0.15471133  0.29163783  0.00188216]
temp40 sorted: [ 0.00188216  0.04484579  0.04655535  0.15471133  0.29163783  0.29597089
  0.31972742  0.3611967   0.39546552  0.55113998]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [50]:
%time
temp41 = np.arange(10)
print("temp41:", temp41)
print(np.add.reduce(temp41))

CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 11 µs
temp41: [0 1 2 3 4 5 6 7 8 9]
45


In [51]:
%time
temp41_2 = np.arange(10)
print("temp41_2:", temp41_2)
print(np.sum(temp41_2))

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 12.6 µs
temp41_2: [0 1 2 3 4 5 6 7 8 9]
45


In [52]:
%time
temp41_2 = np.arange(10)
print("temp41_2:", temp41_2)
print(temp41_2.sum())

CPU times: user 6 µs, sys: 3 µs, total: 9 µs
Wall time: 16.9 µs
temp41_2: [0 1 2 3 4 5 6 7 8 9]
45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [53]:
temp42_1 = [1.1, 2]
temp42_2 = [1.10001, 2]
print(np.allclose(temp42_1, temp42_2))
print(np.array_equal(temp42_1, temp42_2))

True
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [54]:
# temp43 = np.zeros(5)
# temp43.flags.writeable = False
# temp43[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [55]:
temp44 = np.random.rand(10, 2)
x,y = temp44[:,0], temp44[:,1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(x, y)
print(r)
print(theta)

[ 1.19159145  0.65280864  0.55900733  1.02553323  1.12005744  0.71887138
  0.74266229  0.98365458  0.62670157  0.30330817]
[ 0.68567084  0.63210798  0.08055161  0.59369542  0.95367516  0.89459693
  0.13715649  0.76400765  0.10237457  0.37367271]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [56]:
temp45 = np.random.rand(10)
print(temp45)
max_idx = np.argmax(temp45)
temp45[max_idx] = 0
print(temp45)

[ 0.1120882   0.66115942  0.92129784  0.1481994   0.94028512  0.21504889
  0.95481444  0.78189144  0.47684052  0.97824778]
[ 0.1120882   0.66115942  0.92129784  0.1481994   0.94028512  0.21504889
  0.95481444  0.78189144  0.47684052  0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [57]:
temp_46 = np.zeros((5,5), [('xx',float),('yy',float)])
temp_46['xx'], temp_46['yy'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,2,5))
temp_46

array([[( 0.  ,  0. ), ( 0.25,  0. ), ( 0.5 ,  0. ), ( 0.75,  0. ),
        ( 1.  ,  0. )],
       [( 0.  ,  0.5), ( 0.25,  0.5), ( 0.5 ,  0.5), ( 0.75,  0.5),
        ( 1.  ,  0.5)],
       [( 0.  ,  1. ), ( 0.25,  1. ), ( 0.5 ,  1. ), ( 0.75,  1. ),
        ( 1.  ,  1. )],
       [( 0.  ,  1.5), ( 0.25,  1.5), ( 0.5 ,  1.5), ( 0.75,  1.5),
        ( 1.  ,  1.5)],
       [( 0.  ,  2. ), ( 0.25,  2. ), ( 0.5 ,  2. ), ( 0.75,  2. ),
        ( 1.  ,  2. )]],
      dtype=[('xx', '<f8'), ('yy', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [58]:
X47 = np.array([1, 2, 3])
Y47 = np.array([4, 5, 6])
r47 = np.zeros((len(X47),len(Y47)))
for i in range(len(X47)):
    for j in range(len(Y47)):
        r47[i,j] = np.subtract(X47[i], Y47[j])
r47

array([[-3., -4., -5.],
       [-2., -3., -4.],
       [-1., -2., -3.]])

In [59]:
 np.subtract.outer(X47, Y47)

array([[-3, -4, -5],
       [-2, -3, -4],
       [-1, -2, -3]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [60]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype))

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype))
    print(np.finfo(dtype))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
--------------------------------------------------------------

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [61]:
np.set_printoptions(threshold=5)
Z = np.zeros((16,16))
print(Z)
np.set_printoptions(threshold=np.nan)
print(Z)

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [62]:
temp50 = [5, 1, 2, 3, 4]
val50 = 3
temp50_2 = np.abs(np.subtract(temp50,val50))
np.argmin(temp50_2)

3

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [63]:
temp51 = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(temp51)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [64]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

print("====")
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[ 0.          0.5581817   0.19695807  0.38306514  0.47172677  0.0625613
   0.51679023  0.14188128  0.39558686  0.3474584 ]
 [ 0.5581817   0.          0.42473541  0.53612632  0.60625558  0.62065319
   0.57623706  0.43607278  0.1728469   0.23911955]
 [ 0.19695807  0.42473541  0.          0.22619994  0.32257156  0.24666173
   0.59612853  0.06634978  0.2519018   0.18736673]
 [ 0.38306514  0.53612632  0.22619994  0.          0.09643656  0.40901377
   0.82116742  0.28866806  0.38531406  0.32014767]
 [ 0.47172677  0.60625558  0.32257156  0.09643656  0.          0.49184786
   0.91752611  0.38448129  0.46669199  0.40477635]
 [ 0.0625613   0.62065319  0.24666173  0.40901377  0.49184786  0.
   0.54943758  0.19857599  0.45726107  0.40742161]
 [ 0.51679023  0.57623706  0.59612853  0.82116742  0.91752611  0.54943758
   0.          0.53916773  0.54424493  0.56744189]
 [ 0.14188128  0.43607278  0.06634978  0.28866806  0.38448129  0.19857599
   0.53916773  0.          0.26611248  0.21068993]
 [ 0.3955

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [65]:
temp53 = np.arange(10, dtype=np.float32)
print(temp53)
temp53 = temp53.astype(np.int32, copy=False)
print(temp53)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [66]:
# from io import StringIO

# # Fake file 
# s = StringIO("""1, 2, 3, 4, 5\n
#                 6,  ,  , 7, 8\n
#                  ,  , 9,10,11\n""")
# print(type(s))
# Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
# print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [67]:
Z = np.arange(9).reshape(3,3)
print(Z)
for index, value in np.ndenumerate(Z):
    print(index, value)
print("==")
for index in np.ndindex(Z.shape):
    print(index, Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
==
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [68]:
n = 10
p = 3
Z = np.zeros((n,n))
rand_choice = np.random.choice(range(n*n), p, replace=False)
print(rand_choice)
np.put(Z, rand_choice,1)
print(Z)

[46 72 49]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [69]:
temp58 = np.array([[8, 2, 3], [2, 5, 6]])
temp58_row_mean = np.mean(temp58, axis=1, keepdims=True)
print(temp58 - temp58_row_mean)

[[ 3.66666667 -2.33333333 -1.33333333]
 [-2.33333333  0.66666667  1.66666667]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [70]:
temp59 = np.random.randint(0,10,(4,4))
print(temp59)
print("\n")
print(temp59[temp59[:,1].argsort()])

[[7 3 8 7]
 [5 5 8 7]
 [9 7 6 1]
 [0 5 3 2]]


[[7 3 8 7]
 [5 5 8 7]
 [0 5 3 2]
 [9 7 6 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [71]:
temp60 = np.zeros([2, 2])
temp60[0][0] = np.NaN
temp60 = np.isnan(temp60)
print(temp60)
print(temp60.any())

[[ True False]
 [False False]]
True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [72]:
temp61 = np.random.uniform(0,1,10)
pick_temp61 = 0.5
print(temp61)
m = temp61.flat[np.abs(temp61 - pick_temp61).argmin()]
print(m)

[ 0.77186979  0.02111739  0.84500271  0.45095801  0.98718444  0.48946014
  0.02183389  0.75783638  0.18963003  0.07480178]
0.489460135315


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [73]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A)
print(B)
print("\n")
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...] = x + y

print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [74]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [75]:
# Author: Brett Olsen

Z = np.ones(10)
print("Z=",Z)
I = np.random.randint(0,len(Z),20)
print("I=",I)
print("bincount", np.bincount(I, minlength=len(Z)))
Z += np.bincount(I, minlength=len(Z))
print("Z + bincount=", Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

Z= [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
I= [0 8 7 3 0 4 8 2 6 9 0 5 8 9 6 4 8 4 2 5]
bincount [3 0 2 1 3 2 2 1 4 2]
Z + bincount= [ 4.  1.  3.  2.  4.  3.  3.  2.  5.  3.]
[ 7.  1.  5.  3.  7.  5.  5.  3.  9.  5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [76]:

# Author: Alan G Isaac# Autho 

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
print(np.bincount(I))
F = np.bincount(I,X)
print(F)

[0 2 0 2 1 0 0 0 0 1]
[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [77]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [78]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[44 50 52 56]
 [63 47 55 43]
 [52 66 44 60]]
[[44 50 52 56]
 [63 47 55 43]
 [52 66 44 60]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [79]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print("S:", S)
D_sums = np.bincount(S, weights=D)
print("D_sums:", D_sums)
D_counts = np.bincount(S)
print("D_counts:", D_counts)
D_means = D_sums / D_counts
print("D_means:", D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

S: [3 4 6 9 4 0 3 8 4 3 3 3 0 6 1 6 7 1 9 2 4 7 3 0 1 2 4 3 8 9 6 7 2 2 3 4 3
 8 2 2 2 8 5 2 4 1 5 7 3 8 4 5 8 9 7 3 8 7 9 4 4 2 0 8 2 3 2 3 2 2 2 7 2 4
 0 1 4 8 6 9 1 4 8 2 9 4 1 2 6 2 3 0 8 2 2 1 3 4 8 5]
D_sums: [ 4.29102038  4.84653855  8.8961916   8.18824566  8.10134455  2.27530664
  1.59650155  2.68681933  4.7124956   3.73050618]
D_counts: [ 6  8 20 15 15  4  6  7 12  7]
D_means: [ 0.71517006  0.60581732  0.44480958  0.54588304  0.54008964  0.56882666
  0.26608359  0.38383133  0.39270797  0.53292945]
0    0.715170
1    0.605817
2    0.444810
3    0.545883
4    0.540090
5    0.568827
6    0.266084
7    0.383831
8    0.392708
9    0.532929
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [83]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([ 2.45637344,  1.13174559,  0.84299309,  1.31004184,  0.99289472])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)