# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
np.show_config()

1.15.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
zero_3 = np.zeros(10)
zero_3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
print(zero_3.size)
print(zero_3.itemsize)


10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
temp6 = np.zeros(10)
temp6[4] = 1
temp6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
temp7 = np.arange(10, 49)

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
temp7[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
temp9 = np.arange(0, 9)
temp9.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
temp10 = np.array([1,2,0,0,4,0])
np.nonzero(temp10)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
np.random.random((3, 3, 3))

array([[[0.79934357, 0.69755369, 0.58709346],
        [0.45570797, 0.31311266, 0.14919266],
        [0.84272228, 0.12751184, 0.88092122]],

       [[0.6185364 , 0.7220084 , 0.47380153],
        [0.76456493, 0.44770157, 0.23758508],
        [0.10270651, 0.68706642, 0.84676482]],

       [[0.48595968, 0.34682055, 0.45193538],
        [0.82955556, 0.52329668, 0.66184379],
        [0.28339249, 0.9059325 , 0.09591896]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
temp13 = np.random.random((10, 10))
print(temp13)
print("min:", np.min(temp13))
print("max:", np.max(temp13))

[[0.49875508 0.43369691 0.43078972 0.5189673  0.88651887 0.01021416
  0.89595472 0.33284285 0.73279124 0.8618601 ]
 [0.12851547 0.52236632 0.68426514 0.07521657 0.79805988 0.37359791
  0.75353964 0.80505799 0.67420625 0.17218961]
 [0.50305652 0.01457379 0.1837997  0.59480551 0.65303506 0.48006918
  0.98425597 0.47052461 0.7445711  0.390604  ]
 [0.07291461 0.49862618 0.49411046 0.35338315 0.58852189 0.99985107
  0.69503856 0.40701989 0.80349756 0.67754794]
 [0.5394692  0.67059987 0.93561264 0.29310817 0.39769856 0.96384557
  0.72040081 0.27358598 0.7649495  0.37010867]
 [0.71028971 0.7974615  0.09671143 0.76843108 0.76655132 0.71011698
  0.31714685 0.6822463  0.65271211 0.58409945]
 [0.31208653 0.56738223 0.58682284 0.2790394  0.50154966 0.60690284
  0.68744351 0.94644377 0.39890278 0.85044709]
 [0.99950142 0.74232666 0.16539713 0.875033   0.66266183 0.2952988
  0.73876898 0.90679155 0.16245485 0.19381248]
 [0.96878888 0.66736062 0.93181962 0.7543823  0.32332348 0.90539584
  0.68194325 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
temp14 = np.random.random((30))
print(temp14)
print("mean:", np.mean(temp14))

[0.56161751 0.69020211 0.22924714 0.65779193 0.94406625 0.95589071
 0.10556575 0.31907756 0.39680614 0.55127701 0.63629233 0.34933908
 0.42853152 0.20354035 0.51039947 0.26626981 0.36479905 0.46608428
 0.89286945 0.93853833 0.99283252 0.63952704 0.48191854 0.32811031
 0.19254104 0.83732323 0.00995298 0.71638025 0.32949126 0.88969847]
mean: 0.5295327145007614


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
temp15 = np.ones((5, 5))
temp15[1:-1, 1:-1] = 0
temp15

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
temp16 = np.ones((5, 5))
print(temp16)
print(np.pad(temp16, 1, mode='constant'))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
False
nan
False


In [18]:
3*0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [19]:
temp18 = np.diag([1,2,3,4], k=-1)
print(temp18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [20]:
temp19 = np.zeros((8,8))
print(temp19, end="\n\n")
temp19[1::2,::2] = 1
print(temp19, end="\n\n")
temp19[::2,1::2] = 1
print(temp19)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [21]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [22]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [23]:
temp22 = np.random.random((5,5)) * 100
print(temp22)
temp22_min = temp22.min()
temp22_max = temp22.max()
temp22_normal = (temp22-temp22_min) / (temp22_max-temp22_min)
temp22_normal

[[58.39936311 25.46265013 79.17568645 70.88172348 11.11378811]
 [14.96316763  9.88666776 93.69334117 26.70838983 26.33057805]
 [68.12591101 91.1902464  16.02076861 43.16601484 95.9997946 ]
 [18.06391081 62.99921294 51.41587143 28.01016217 81.40824962]
 [ 7.72930882 31.29356311 26.14999656 47.35620827 83.68231193]]


array([[0.57403167, 0.20089774, 0.80940279, 0.71544202, 0.03834214],
       [0.08195105, 0.02444032, 0.97387062, 0.2150105 , 0.21073034],
       [0.68422193, 0.94551352, 0.09393241, 0.40145589, 1.        ],
       [0.11707879, 0.62614252, 0.49491698, 0.22975803, 0.83469509],
       [0.        , 0.26695508, 0.20868456, 0.44892581, 0.86045752]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [24]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [25]:
temp24_1 = np.random.random((5, 3)) * 10
print(temp24_1, end="\n\n")
temp24_2 = np.random.random((3, 2)) * 10
print(temp24_2, end="\n\n")
temp24_3 = np.dot(temp24_1, temp24_2)
print(temp24_3, end="\n\n")


[[4.68383245 1.0750208  0.20166319]
 [3.2180541  5.07626152 2.79419471]
 [9.91714714 0.50966494 2.19767008]
 [6.63838354 8.89358965 3.19390531]
 [0.58430044 4.46933173 3.4070459 ]]

[[8.22150498 4.81910354]
 [9.10503726 6.94998876]
 [5.24019229 9.37043008]]

[[ 49.35301006  31.93292675]
 [ 87.31891565  76.97090255]
 [ 97.69060669  71.92703831]
 [152.29064651 123.72967215]
 [ 63.35083649  65.80309496]]



#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [26]:
temp25 = np.arange(3, 9)
temp25[(3 < temp25) & (temp25 <= 8)] *= -1
temp25

array([ 3, -4, -5, -6, -7, -8])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = arange(8)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([0., 1., 2., 3., 4., 5., 6., 7.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9223372036854775808]
[-9.22337204e+18]


/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  from ipykernel import kernelapp as app


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [30]:
temp29 = np.random.uniform(-10,+10,10)
print(temp29, end="\n\n")
temp29 = np.copysign(np.floor(np.abs(temp29)), temp29)
print(temp29)

[-0.96374722 -3.93798749 -3.86733304  0.3941865   9.96454811  6.16881747
  0.73275134  0.09146512  3.92044408 -8.46199152]

[-0. -3. -3.  0.  9.  6.  0.  0.  3. -8.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [31]:
temp30_1 = np.arange(1, 5)
temp30_2 = np.arange(3, 6)

In [32]:
%time
print(np.intersect1d(temp30_1, temp30_2))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.91 µs
[3 4]


In [33]:
%time
print(set(temp30_1) & set(temp30_2))

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 10 µs
{3, 4}


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [34]:
np.int16(32000) * np.int16(3)

/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: overflow encountered in short_scalars
  if __name__ == '__main__':


30464

In [35]:
default_setting = np.seterr()
default_setting

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [36]:
old_settings = np.seterr(all='ignore')
old_settings

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [37]:
np.int16(32000) * np.int16(3)

30464

In [38]:
old_settings = np.seterr(**default_setting)  #seterr to known value
np.int16(32000) * np.int16(3)

/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in short_scalars
  from ipykernel import kernelapp as app


30464

In [39]:
with np.errstate(over='ignore'):
    np.int16(32000) * np.int16(3)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [40]:
print("np.sqrt(-1):", np.sqrt(-1))
print("np.emath.sqrt(-1):", np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

np.sqrt(-1): nan
np.emath.sqrt(-1): 1j


/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':
/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:3: RuntimeWarning: invalid value encountered in sqrt
  app.launch_new_instance()


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [41]:
today     = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow  = today + np.timedelta64(1, 'D')
print("today:", today)
print("yesterday:", yesterday)
print("tomorrow:", tomorrow)

today: 2018-11-13
yesterday: 2018-11-12
tomorrow: 2018-11-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [42]:
np.arange(np.datetime64('2018-07-01', 'D'), np.datetime64('2018-08-01', 'D'))

array(['2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04',
       '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08',
       '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12',
       '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16',
       '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20',
       '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24',
       '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28',
       '2018-07-29', '2018-07-30', '2018-07-31'], dtype='datetime64[D]')

In [43]:
np.arange(np.datetime64('2018-07-01', 'D'), np.datetime64('2018-07-31', 'D') + 1)

array(['2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04',
       '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08',
       '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12',
       '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16',
       '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20',
       '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24',
       '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28',
       '2018-07-29', '2018-07-30', '2018-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [44]:
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
np.add(A, B, out=B)
np.divide(-A, 2, out=A)
np.multiply(A, B)

array([[-0.01870266, -0.51771518],
       [-0.13711087, -0.03241348]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [45]:
temp_rand_36 = np.random.rand(3) * 10
print("temp_rand_36:", temp_rand_36)
print(np.floor(temp_rand_36))
print(np.ceil(temp_rand_36))
print(temp_rand_36.astype(np.int32))
print(np.trunc(temp_rand_36))
print(temp_rand_36 - temp_rand_36 % 1)

temp_rand_36: [3.84846063 2.15473328 5.48742718]
[3. 2. 5.]
[4. 3. 6.]
[3 2 5]
[3. 2. 5.]
[3. 2. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [46]:
np.zeros((5, 5)) + np.arange(0, 5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [47]:
def get_10_num():
    for i in range(10):
        yield i
np.fromiter(get_10_num(), int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [48]:
np.linspace(0, 1, num=11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [49]:
temp40 = np.random.rand(10)
print("temp40:", temp40)
print("temp40 sorted:", np.sort(temp40))

temp40: [0.94100323 0.23871317 0.13102514 0.36059377 0.73923936 0.43103232
 0.05776592 0.86057892 0.97647919 0.05343773]
temp40 sorted: [0.05343773 0.05776592 0.13102514 0.23871317 0.36059377 0.43103232
 0.73923936 0.86057892 0.94100323 0.97647919]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [50]:
%time
temp41 = np.arange(10)
print("temp41:", temp41)
print(np.add.reduce(temp41))

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 7.15 µs
temp41: [0 1 2 3 4 5 6 7 8 9]
45


In [51]:
%time
temp41_2 = np.arange(10)
print("temp41_2:", temp41_2)
print(np.sum(temp41_2))

CPU times: user 5 µs, sys: 1e+03 ns, total: 6 µs
Wall time: 10 µs
temp41_2: [0 1 2 3 4 5 6 7 8 9]
45


In [52]:
%time
temp41_2 = np.arange(10)
print("temp41_2:", temp41_2)
print(temp41_2.sum())

CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 11.2 µs
temp41_2: [0 1 2 3 4 5 6 7 8 9]
45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [53]:
temp42_1 = [1.1, 2]
temp42_2 = [1.10001, 2]
print(np.allclose(temp42_1, temp42_2))
print(np.array_equal(temp42_1, temp42_2))

True
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [54]:
# temp43 = np.zeros(5)
# temp43.flags.writeable = False
# temp43[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [55]:
temp44 = np.random.rand(10, 2)
x,y = temp44[:,0], temp44[:,1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(x, y)
print(r)
print(theta)

[0.77320461 0.58007683 0.70867064 0.85663444 0.68520546 1.12471719
 0.79150671 0.824703   1.23188543 0.6076627 ]
[0.40879588 0.37956343 0.60241022 1.01121249 1.29430601 0.65547116
 0.59544791 0.1581946  0.68319709 0.32788267]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [56]:
temp45 = np.random.rand(10)
print(temp45)
max_idx = np.argmax(temp45)
temp45[max_idx] = 0
print(temp45)

[0.45990933 0.74563918 0.62538563 0.21739259 0.5241781  0.27539643
 0.74395774 0.81059264 0.23845802 0.26982026]
[0.45990933 0.74563918 0.62538563 0.21739259 0.5241781  0.27539643
 0.74395774 0.         0.23845802 0.26982026]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [57]:
temp_46 = np.zeros((5,5), [('xx',float),('yy',float)])
temp_46['xx'], temp_46['yy'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,2,5))
temp_46

array([[(0.  , 0. ), (0.25, 0. ), (0.5 , 0. ), (0.75, 0. ), (1.  , 0. )],
       [(0.  , 0.5), (0.25, 0.5), (0.5 , 0.5), (0.75, 0.5), (1.  , 0.5)],
       [(0.  , 1. ), (0.25, 1. ), (0.5 , 1. ), (0.75, 1. ), (1.  , 1. )],
       [(0.  , 1.5), (0.25, 1.5), (0.5 , 1.5), (0.75, 1.5), (1.  , 1.5)],
       [(0.  , 2. ), (0.25, 2. ), (0.5 , 2. ), (0.75, 2. ), (1.  , 2. )]],
      dtype=[('xx', '<f8'), ('yy', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [58]:
X47 = np.array([1, 2, 3])
Y47 = np.array([4, 5, 6])
r47 = np.zeros((len(X47),len(Y47)))
for i in range(len(X47)):
    for j in range(len(Y47)):
        r47[i,j] = np.subtract(X47[i], Y47[j])
r47

array([[-3., -4., -5.],
       [-2., -3., -4.],
       [-1., -2., -3.]])

In [59]:
 np.subtract.outer(X47, Y47)

array([[-3, -4, -5],
       [-2, -3, -4],
       [-1, -2, -3]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [60]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype))

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype))
    print(np.finfo(dtype))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
--------------------------------------------------------------

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [61]:
np.set_printoptions(threshold=5)
Z = np.zeros((16,16))
print(Z)
np.set_printoptions(threshold=np.nan)
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [62]:
temp50 = [5, 1, 2, 3, 4]
val50 = 3
temp50_2 = np.abs(np.subtract(temp50,val50))
np.argmin(temp50_2)

3

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [63]:
temp51 = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(temp51)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [64]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

print("====")
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.6109172  0.53539591 0.33508583 0.77716795 1.03762236
  0.59155592 0.37920674 0.70160228 0.78458048]
 [0.6109172  0.         0.95664923 0.51518743 0.19835658 0.83902381
  0.20800355 0.86487854 0.09689302 0.64030156]
 [0.53539591 0.95664923 0.         0.44231785 1.04474216 0.8895332
  0.81928298 0.16542046 1.05249435 0.69540801]
 [0.33508583 0.51518743 0.44231785 0.         0.60909724 0.70347133
  0.38511576 0.37205874 0.61055436 0.45139429]
 [0.77716795 0.19835658 1.04474216 0.60909724 0.         0.7343689
  0.22546263 0.97879753 0.17178948 0.58322385]
 [1.03762236 0.83902381 0.8895332  0.70347133 0.7343689  0.
  0.64056089 0.94852059 0.88021033 0.25363484]
 [0.59155592 0.20800355 0.81928298 0.38511576 0.22546263 0.64056089
  0.         0.75641394 0.27767895 0.43266734]
 [0.37920674 0.86487854 0.16542046 0.37205874 0.97879753 0.94852059
  0.75641394 0.         0.96177117 0.72615745]
 [0.70160228 0.09689302 1.05249435 0.61055436 0.17178948 0.88021033
  0.27767895 0.9617711

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [65]:
temp53 = np.arange(10, dtype=np.float32)
print(temp53)
temp53 = temp53.astype(np.int32, copy=False)
print(temp53)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [66]:
# from io import StringIO

# # Fake file 
# s = StringIO("""1, 2, 3, 4, 5\n
#                 6,  ,  , 7, 8\n
#                  ,  , 9,10,11\n""")
# print(type(s))
# Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
# print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [67]:
Z = np.arange(9).reshape(3,3)
print(Z)
for index, value in np.ndenumerate(Z):
    print(index, value)
print("==")
for index in np.ndindex(Z.shape):
    print(index, Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
==
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [68]:
n = 10
p = 3
Z = np.zeros((n,n))
rand_choice = np.random.choice(range(n*n), p, replace=False)
print(rand_choice)
np.put(Z, rand_choice,1)
print(Z)

[57  4 69]
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [69]:
temp58 = np.array([[8, 2, 3], [2, 5, 6]])
temp58_row_mean = np.mean(temp58, axis=1, keepdims=True)
print(temp58 - temp58_row_mean)

[[ 3.66666667 -2.33333333 -1.33333333]
 [-2.33333333  0.66666667  1.66666667]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [70]:
temp59 = np.random.randint(0,10,(4,4))
print(temp59)
print("\n")
print(temp59[temp59[:,1].argsort()])

[[3 9 5 0]
 [4 1 8 4]
 [1 0 1 4]
 [3 4 9 2]]


[[1 0 1 4]
 [4 1 8 4]
 [3 4 9 2]
 [3 9 5 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [71]:
temp60 = np.zeros([2, 2])
temp60[0][0] = np.NaN
temp60 = np.isnan(temp60)
print(temp60)
print(temp60.any())

[[ True False]
 [False False]]
True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [72]:
temp61 = np.random.uniform(0,1,10)
pick_temp61 = 0.5
print(temp61)
m = temp61.flat[np.abs(temp61 - pick_temp61).argmin()]
print(m)

[0.71857073 0.53657483 0.52175127 0.57120863 0.32066492 0.10762765
 0.21433955 0.99375817 0.14736692 0.89326479]
0.5217512655006294


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [73]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A)
print(B)
print("\n")
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...] = x + y

print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [74]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [75]:
# Author: Brett Olsen

Z = np.ones(10)
print("Z=",Z)
I = np.random.randint(0,len(Z),20)
print("I=",I)
print("bincount", np.bincount(I, minlength=len(Z)))
Z += np.bincount(I, minlength=len(Z))
print("Z + bincount=", Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

Z= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
I= [9 9 5 8 7 0 3 6 2 1 6 3 7 7 3 4 9 6 9 0]
bincount [2 1 1 3 1 1 3 3 1 4]
Z + bincount= [3. 2. 2. 4. 2. 2. 4. 4. 2. 5.]
[5. 3. 3. 7. 3. 3. 7. 7. 3. 9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [76]:

# Author: Alan G Isaac# Autho 

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
print(np.bincount(I))
F = np.bincount(I,X)
print(F)

[0 2 0 2 1 0 0 0 0 1]
[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [77]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [78]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[61 61 48 59]
 [56 48 49 44]
 [50 69 55 58]]
[[61 61 48 59]
 [56 48 49 44]
 [50 69 55 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [79]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print("S:", S)
D_sums = np.bincount(S, weights=D)
print("D_sums:", D_sums)
D_counts = np.bincount(S)
print("D_counts:", D_counts)
D_means = D_sums / D_counts
print("D_means:", D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

S: [5 8 4 4 1 9 0 9 3 1 2 6 2 8 4 7 0 7 5 6 5 8 8 9 1 9 0 0 5 1 3 3 8 9 4 1 7
 1 7 4 7 2 2 4 1 2 5 4 7 5 0 8 1 2 5 5 6 2 8 9 4 5 7 2 7 6 3 0 7 9 1 1 9 9
 2 6 9 3 6 4 4 1 0 4 6 8 4 6 1 0 0 6 9 0 5 4 1 7 7 7]
D_sums: [5.75235661 4.28744693 5.26470306 2.10842172 7.19460567 3.9281524
 5.15398168 5.76824997 4.83573221 4.72298808]
D_counts: [10 13  9  5 13 10  9 12  8 11]
D_means: [0.57523566 0.32980361 0.58496701 0.42168434 0.55343121 0.39281524
 0.57266463 0.4806875  0.60446653 0.42936255]
0    0.575236
1    0.329804
2    0.584967
3    0.421684
4    0.553431
5    0.392815
6    0.572665
7    0.480687
8    0.604467
9    0.429363
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [80]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.10159571, 0.35873839, 1.27962398, 0.84284416, 0.9567253 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\]

In [81]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [82]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
sol1 = A * B.reshape(5,5,1)
sol2 = A * B[:,:,None]

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [83]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [84]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
print("faces:{0}\n".format(faces))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
print("F:{0}\n".format(F))
F = F.reshape(len(F)*3,2)
print("F reshape:{0}\n".format(F))
F = np.sort(F,axis=1)
print("F reshape sort:{0}\n".format(F))
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

faces:[[18 66 86]
 [12 73 40]
 [88 74 81]
 [39 64 31]
 [30 50 15]
 [26 87 93]
 [84 44 21]
 [ 5 28 42]
 [92 45  6]
 [ 8 73 32]]

F:[[18 66 66 86 86 18]
 [12 73 73 40 40 12]
 [88 74 74 81 81 88]
 [39 64 64 31 31 39]
 [30 50 50 15 15 30]
 [26 87 87 93 93 26]
 [84 44 44 21 21 84]
 [ 5 28 28 42 42  5]
 [92 45 45  6  6 92]
 [ 8 73 73 32 32  8]]

F reshape:[[18 66]
 [66 86]
 [86 18]
 [12 73]
 [73 40]
 [40 12]
 [88 74]
 [74 81]
 [81 88]
 [39 64]
 [64 31]
 [31 39]
 [30 50]
 [50 15]
 [15 30]
 [26 87]
 [87 93]
 [93 26]
 [84 44]
 [44 21]
 [21 84]
 [ 5 28]
 [28 42]
 [42  5]
 [92 45]
 [45  6]
 [ 6 92]
 [ 8 73]
 [73 32]
 [32  8]]

F reshape sort:[[18 66]
 [66 86]
 [18 86]
 [12 73]
 [40 73]
 [12 40]
 [74 88]
 [74 81]
 [81 88]
 [39 64]
 [31 64]
 [31 39]
 [30 50]
 [15 50]
 [15 30]
 [26 87]
 [87 93]
 [26 93]
 [44 84]
 [21 44]
 [21 84]
 [ 5 28]
 [28 42]
 [ 5 42]
 [45 92]
 [ 6 45]
 [ 6 92]
 [ 8 73]
 [32 73]
 [ 8 32]]

[( 5, 28) ( 5, 42) ( 6, 45) ( 6, 92) ( 8, 32) ( 8, 73) (12, 40) (12, 73)
 (15, 30) (15, 5

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [85]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
print("C:", C)
A = np.repeat(np.arange(len(C)), C)
print("A:", A)

C: [0 2 1 1 2 0 1]
A: [1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [86]:
??cumsum

In [87]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    print("a:", a)
    ret = np.cumsum(a, dtype=float)
    print("ret:", ret)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print("moving_average:", moving_average(Z, n=3))

a: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
ret: [  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
moving_average: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [92]:
??stride_tricks

In [102]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    print(shape)
    strides = (a.itemsize, a.itemsize)
    print(strides)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
input_arr = np.arange(10)
Z = rolling(np.arange(10), 3)
print(Z)

(8, 3)
(8, 8)
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)