# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
np.show_config()

1.15.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
zero_3 = np.zeros(10)
zero_3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
print(zero_3.size)
print(zero_3.itemsize)


10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
temp6 = np.zeros(10)
temp6[4] = 1
temp6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
temp7 = np.arange(10, 49)

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
temp7[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
temp9 = np.arange(0, 9)
temp9.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
temp10 = np.array([1,2,0,0,4,0])
np.nonzero(temp10)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
np.random.random((3, 3, 3))

array([[[0.94782208, 0.70642262, 0.68409856],
        [0.23619077, 0.05708091, 0.05893342],
        [0.74763858, 0.76979843, 0.94262959]],

       [[0.7132257 , 0.71141513, 0.03109565],
        [0.95458521, 0.70737913, 0.3287997 ],
        [0.89712821, 0.48372611, 0.48115606]],

       [[0.5114701 , 0.78949858, 0.21790357],
        [0.62589653, 0.7143814 , 0.886328  ],
        [0.4397658 , 0.14883246, 0.8177847 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
temp13 = np.random.random((10, 10))
print(temp13)
print("min:", np.min(temp13))
print("max:", np.max(temp13))

[[0.93939368 0.41327913 0.13321198 0.13609152 0.78245172 0.30277751
  0.66170811 0.93382072 0.4660674  0.51426232]
 [0.44338863 0.80445333 0.01602493 0.37468461 0.76346922 0.25802452
  0.65314986 0.61480964 0.67093242 0.35859754]
 [0.64602995 0.441492   0.75435833 0.21910763 0.42452226 0.61692672
  0.62531789 0.26996325 0.72276179 0.67571665]
 [0.13512638 0.649257   0.34345884 0.69277718 0.04742125 0.88337357
  0.67522372 0.7569614  0.32146867 0.22615476]
 [0.63080493 0.19331985 0.79457701 0.96674263 0.23560535 0.39993025
  0.11400554 0.78183001 0.49887918 0.27441655]
 [0.96372529 0.59505893 0.86019903 0.93707564 0.33866397 0.23669807
  0.77012857 0.61523579 0.43216304 0.18530715]
 [0.25466607 0.76375592 0.52155585 0.40378121 0.61690516 0.63913524
  0.84520353 0.68070908 0.90707007 0.79777359]
 [0.75611989 0.84017472 0.60485647 0.66138405 0.671263   0.54317072
  0.27022052 0.7921362  0.04843416 0.47870264]
 [0.09958483 0.8878188  0.48903116 0.80453613 0.23549655 0.99247867
  0.37391018

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
temp14 = np.random.random((30))
print(temp14)
print("mean:", np.mean(temp14))

[0.35810502 0.99620134 0.43170187 0.08313892 0.13591443 0.2634648
 0.82522771 0.54384358 0.81562153 0.44198517 0.24202555 0.37454693
 0.01421234 0.7412372  0.93899981 0.73881258 0.08516261 0.35054351
 0.42657424 0.38960946 0.10223103 0.5533462  0.45756275 0.41423208
 0.62760834 0.26916374 0.9969966  0.7735163  0.32400957 0.71300832]
mean: 0.4809534504506158


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
temp15 = np.ones((5, 5))
temp15[1:-1, 1:-1] = 0
temp15

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
temp16 = np.ones((5, 5))
print(temp16)
print(np.pad(temp16, 1, mode='constant'))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
False
nan
False


In [18]:
3*0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [19]:
temp18 = np.diag([1,2,3,4], k=-1)
print(temp18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [20]:
temp19 = np.zeros((8,8))
print(temp19, end="\n\n")
temp19[1::2,::2] = 1
print(temp19, end="\n\n")
temp19[::2,1::2] = 1
print(temp19)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [21]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [22]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [23]:
temp22 = np.random.random((5,5)) * 100
print(temp22)
temp22_min = temp22.min()
temp22_max = temp22.max()
temp22_normal = (temp22-temp22_min) / (temp22_max-temp22_min)
temp22_normal

[[ 1.51725964 59.77183124 59.68241034 58.33126692 79.26207823]
 [97.46280535  2.64828604  4.27353539 74.19428674 76.34443663]
 [97.37721749 21.43711432 83.79107095 48.84856674 18.79325892]
 [21.69166129 61.56875827 16.18268674  0.42367013 75.31072866]
 [99.25358586 87.6957112  83.43704614 93.86287932 25.72931825]]


array([[0.01106537, 0.60050806, 0.59960327, 0.58593186, 0.79771805],
       [0.98188018, 0.02250954, 0.03895445, 0.74644014, 0.76819621],
       [0.98101417, 0.2126223 , 0.84354419, 0.48998217, 0.18587073],
       [0.21519791, 0.61869008, 0.15945593, 0.        , 0.75773674],
       [1.        , 0.88305287, 0.83996202, 0.94545471, 0.25605251]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [24]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [25]:
temp24_1 = np.random.random((5, 3)) * 10
print(temp24_1, end="\n\n")
temp24_2 = np.random.random((3, 2)) * 10
print(temp24_2, end="\n\n")
temp24_3 = np.dot(temp24_1, temp24_2)
print(temp24_3, end="\n\n")


[[7.62553939 6.42025492 4.71400151]
 [8.01082952 9.3461572  2.03110677]
 [7.4346882  2.93168018 3.97942882]
 [2.55542008 2.35466339 1.22295522]
 [0.91064084 5.43994366 8.8088981 ]]

[[3.60391018 3.5522168 ]
 [2.33963355 2.16072532]
 [9.84106098 7.23142827]]

[[ 88.89357911  75.04894031]
 [ 70.72513848  63.33848462]
 [ 72.81480746  61.52113403]
 [ 26.75373085  23.00889995]
 [102.6982458   78.68993245]]



#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [26]:
temp25 = np.arange(3, 9)
temp25[(3 < temp25) & (temp25 <= 8)] *= -1
temp25

array([ 3, -4, -5, -6, -7, -8])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = arange(8)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([0., 1., 2., 3., 4., 5., 6., 7.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9223372036854775808]
[-9.22337204e+18]


/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  from ipykernel import kernelapp as app


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [30]:
temp29 = np.random.uniform(-10,+10,10)
print(temp29, end="\n\n")
temp29 = np.copysign(np.floor(np.abs(temp29)), temp29)
print(temp29)

[-2.79165052  7.0674472   0.52538832  3.89570103 -9.35926302 -8.66934475
 -7.09954957 -1.82698329 -6.60761396  6.07544817]

[-2.  7.  0.  3. -9. -8. -7. -1. -6.  6.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [31]:
temp30_1 = np.arange(1, 5)
temp30_2 = np.arange(3, 6)

In [32]:
%time
print(np.intersect1d(temp30_1, temp30_2))

CPU times: user 5 µs, sys: 1e+03 ns, total: 6 µs
Wall time: 202 µs
[3 4]


In [33]:
%time
print(set(temp30_1) & set(temp30_2))

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 11.9 µs
{3, 4}


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [34]:
np.int16(32000) * np.int16(3)

/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: overflow encountered in short_scalars
  if __name__ == '__main__':


30464

In [35]:
default_setting = np.seterr()
default_setting

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [36]:
old_settings = np.seterr(all='ignore')
old_settings

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [37]:
np.int16(32000) * np.int16(3)

30464

In [38]:
old_settings = np.seterr(**default_setting)  #seterr to known value
np.int16(32000) * np.int16(3)

/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in short_scalars
  from ipykernel import kernelapp as app


30464

In [39]:
with np.errstate(over='ignore'):
    np.int16(32000) * np.int16(3)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [40]:
print("np.sqrt(-1):", np.sqrt(-1))
print("np.emath.sqrt(-1):", np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

np.sqrt(-1): nan
np.emath.sqrt(-1): 1j


/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':
/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:3: RuntimeWarning: invalid value encountered in sqrt
  app.launch_new_instance()


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [41]:
today     = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow  = today + np.timedelta64(1, 'D')
print("today:", today)
print("yesterday:", yesterday)
print("tomorrow:", tomorrow)

today: 2018-11-15
yesterday: 2018-11-14
tomorrow: 2018-11-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [42]:
np.arange(np.datetime64('2018-07-01', 'D'), np.datetime64('2018-08-01', 'D'))

array(['2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04',
       '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08',
       '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12',
       '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16',
       '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20',
       '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24',
       '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28',
       '2018-07-29', '2018-07-30', '2018-07-31'], dtype='datetime64[D]')

In [43]:
np.arange(np.datetime64('2018-07-01', 'D'), np.datetime64('2018-07-31', 'D') + 1)

array(['2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04',
       '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08',
       '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12',
       '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16',
       '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20',
       '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24',
       '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28',
       '2018-07-29', '2018-07-30', '2018-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [44]:
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
np.add(A, B, out=B)
np.divide(-A, 2, out=A)
np.multiply(A, B)

array([[-0.13849201, -0.42752507],
       [-0.33061455, -0.41590065]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [45]:
temp_rand_36 = np.random.rand(3) * 10
print("temp_rand_36:", temp_rand_36)
print(np.floor(temp_rand_36))
print(np.ceil(temp_rand_36))
print(temp_rand_36.astype(np.int32))
print(np.trunc(temp_rand_36))
print(temp_rand_36 - temp_rand_36 % 1)

temp_rand_36: [8.2654279  5.40395162 3.95670811]
[8. 5. 3.]
[9. 6. 4.]
[8 5 3]
[8. 5. 3.]
[8. 5. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [46]:
np.zeros((5, 5)) + np.arange(0, 5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [47]:
def get_10_num():
    for i in range(10):
        yield i
np.fromiter(get_10_num(), int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [48]:
np.linspace(0, 1, num=11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [49]:
temp40 = np.random.rand(10)
print("temp40:", temp40)
print("temp40 sorted:", np.sort(temp40))

temp40: [0.74053518 0.23593088 0.63680774 0.9761167  0.43722997 0.91607146
 0.62371088 0.12521214 0.82413296 0.15987433]
temp40 sorted: [0.12521214 0.15987433 0.23593088 0.43722997 0.62371088 0.63680774
 0.74053518 0.82413296 0.91607146 0.9761167 ]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [50]:
%time
temp41 = np.arange(10)
print("temp41:", temp41)
print(np.add.reduce(temp41))

CPU times: user 6 µs, sys: 1e+03 ns, total: 7 µs
Wall time: 13.8 µs
temp41: [0 1 2 3 4 5 6 7 8 9]
45


In [51]:
%time
temp41_2 = np.arange(10)
print("temp41_2:", temp41_2)
print(np.sum(temp41_2))

CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 13.1 µs
temp41_2: [0 1 2 3 4 5 6 7 8 9]
45


In [52]:
%time
temp41_2 = np.arange(10)
print("temp41_2:", temp41_2)
print(temp41_2.sum())

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 11.2 µs
temp41_2: [0 1 2 3 4 5 6 7 8 9]
45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [53]:
temp42_1 = [1.1, 2]
temp42_2 = [1.10001, 2]
print(np.allclose(temp42_1, temp42_2))
print(np.array_equal(temp42_1, temp42_2))

True
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [54]:
# temp43 = np.zeros(5)
# temp43.flags.writeable = False
# temp43[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [55]:
temp44 = np.random.rand(10, 2)
x,y = temp44[:,0], temp44[:,1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(x, y)
print(r)
print(theta)

[1.22624782 1.2159773  0.67562539 0.95775622 1.05827679 0.89045879
 0.8743641  0.94669286 0.79924738 0.82617996]
[0.76288658 0.66287287 0.85159643 0.31113014 0.77010491 0.62268426
 1.08349951 0.27526833 0.13323484 0.4284723 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [56]:
temp45 = np.random.rand(10)
print(temp45)
max_idx = np.argmax(temp45)
temp45[max_idx] = 0
print(temp45)

[0.03591739 0.96655274 0.30472617 0.28446097 0.97098957 0.02207922
 0.4258866  0.45455474 0.03922488 0.41825223]
[0.03591739 0.96655274 0.30472617 0.28446097 0.         0.02207922
 0.4258866  0.45455474 0.03922488 0.41825223]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [57]:
temp_46 = np.zeros((5,5), [('xx',float),('yy',float)])
temp_46['xx'], temp_46['yy'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,2,5))
temp_46

array([[(0.  , 0. ), (0.25, 0. ), (0.5 , 0. ), (0.75, 0. ), (1.  , 0. )],
       [(0.  , 0.5), (0.25, 0.5), (0.5 , 0.5), (0.75, 0.5), (1.  , 0.5)],
       [(0.  , 1. ), (0.25, 1. ), (0.5 , 1. ), (0.75, 1. ), (1.  , 1. )],
       [(0.  , 1.5), (0.25, 1.5), (0.5 , 1.5), (0.75, 1.5), (1.  , 1.5)],
       [(0.  , 2. ), (0.25, 2. ), (0.5 , 2. ), (0.75, 2. ), (1.  , 2. )]],
      dtype=[('xx', '<f8'), ('yy', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [58]:
X47 = np.array([1, 2, 3])
Y47 = np.array([4, 5, 6])
r47 = np.zeros((len(X47),len(Y47)))
for i in range(len(X47)):
    for j in range(len(Y47)):
        r47[i,j] = np.subtract(X47[i], Y47[j])
r47

array([[-3., -4., -5.],
       [-2., -3., -4.],
       [-1., -2., -3.]])

In [59]:
 np.subtract.outer(X47, Y47)

array([[-3, -4, -5],
       [-2, -3, -4],
       [-1, -2, -3]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [60]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype))

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype))
    print(np.finfo(dtype))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
--------------------------------------------------------------

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [61]:
np.set_printoptions(threshold=5)
Z = np.zeros((16,16))
print(Z)
np.set_printoptions(threshold=np.nan)
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [62]:
temp50 = [5, 1, 2, 3, 4]
val50 = 3
temp50_2 = np.abs(np.subtract(temp50,val50))
np.argmin(temp50_2)

3

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [63]:
temp51 = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(temp51)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [64]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

print("====")
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.3236369  0.36215663 0.70243146 0.27018601 0.7597012
  0.48419998 0.52636571 0.30874347 0.34283022]
 [0.3236369  0.         0.20984347 0.43905456 0.59363743 0.61017322
  0.5666458  0.61916338 0.6321982  0.14214658]
 [0.36215663 0.20984347 0.         0.34772983 0.60809019 0.42324346
  0.38453507 0.43658699 0.64457029 0.3501102 ]
 [0.70243146 0.43905456 0.34772983 0.         0.95553019 0.30982461
  0.62074262 0.66230862 0.99219004 0.55681167]
 [0.27018601 0.59363743 0.60809019 0.95553019 0.         0.96138994
  0.57935299 0.60251965 0.03856256 0.59596486]
 [0.7597012  0.61017322 0.42324346 0.30982461 0.96138994 0.
  0.46281351 0.48491602 0.99244768 0.75054554]
 [0.48419998 0.5666458  0.38453507 0.62074262 0.57935299 0.46281351
  0.         0.05262399 0.60112401 0.68665706]
 [0.52636571 0.61916338 0.43658699 0.66230862 0.60251965 0.48491602
  0.05262399 0.         0.62168876 0.73841298]
 [0.30874347 0.6321982  0.64457029 0.99219004 0.03856256 0.99244768
  0.60112401 0.621688

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [65]:
temp53 = np.arange(10, dtype=np.float32)
print(temp53)
temp53 = temp53.astype(np.int32, copy=False)
print(temp53)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [66]:
# from io import StringIO

# # Fake file 
# s = StringIO("""1, 2, 3, 4, 5\n
#                 6,  ,  , 7, 8\n
#                  ,  , 9,10,11\n""")
# print(type(s))
# Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
# print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [67]:
Z = np.arange(9).reshape(3,3)
print(Z)
for index, value in np.ndenumerate(Z):
    print(index, value)
print("==")
for index in np.ndindex(Z.shape):
    print(index, Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
==
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [68]:
n = 10
p = 3
Z = np.zeros((n,n))
rand_choice = np.random.choice(range(n*n), p, replace=False)
print(rand_choice)
np.put(Z, rand_choice,1)
print(Z)

[18  6 36]
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [69]:
temp58 = np.array([[8, 2, 3], [2, 5, 6]])
temp58_row_mean = np.mean(temp58, axis=1, keepdims=True)
print(temp58 - temp58_row_mean)

[[ 3.66666667 -2.33333333 -1.33333333]
 [-2.33333333  0.66666667  1.66666667]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [70]:
temp59 = np.random.randint(0,10,(4,4))
print(temp59)
print("\n")
print(temp59[temp59[:,1].argsort()])

[[8 9 0 6]
 [1 9 2 7]
 [9 3 4 1]
 [9 0 8 9]]


[[9 0 8 9]
 [9 3 4 1]
 [8 9 0 6]
 [1 9 2 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [71]:
temp60 = np.zeros([2, 2])
temp60[0][0] = np.NaN
temp60 = np.isnan(temp60)
print(temp60)
print(temp60.any())

[[ True False]
 [False False]]
True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [72]:
temp61 = np.random.uniform(0,1,10)
pick_temp61 = 0.5
print(temp61)
m = temp61.flat[np.abs(temp61 - pick_temp61).argmin()]
print(m)

[0.84180547 0.53793689 0.29194934 0.4669566  0.95660438 0.46458234
 0.52751682 0.61134718 0.32778893 0.80259408]
0.5275168243676184


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [73]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A)
print(B)
print("\n")
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...] = x + y

print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [74]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [75]:
# Author: Brett Olsen

Z = np.ones(10)
print("Z=",Z)
I = np.random.randint(0,len(Z),20)
print("I=",I)
print("bincount", np.bincount(I, minlength=len(Z)))
Z += np.bincount(I, minlength=len(Z))
print("Z + bincount=", Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

Z= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
I= [6 5 8 5 3 1 5 6 3 7 8 3 5 9 9 4 8 2 0 2]
bincount [1 1 2 3 1 4 2 1 3 2]
Z + bincount= [2. 2. 3. 4. 2. 5. 3. 2. 4. 3.]
[3. 3. 5. 7. 3. 9. 5. 3. 7. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [76]:

# Author: Alan G Isaac# Autho 

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
print(np.bincount(I))
F = np.bincount(I,X)
print(F)

[0 2 0 2 1 0 0 0 0 1]
[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [77]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [78]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[56 48 51 46]
 [63 42 69 46]
 [67 48 60 49]]
[[56 48 51 46]
 [63 42 69 46]
 [67 48 60 49]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [79]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print("S:", S)
D_sums = np.bincount(S, weights=D)
print("D_sums:", D_sums)
D_counts = np.bincount(S)
print("D_counts:", D_counts)
D_means = D_sums / D_counts
print("D_means:", D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

S: [7 2 2 9 2 8 2 5 3 6 1 1 3 1 2 1 3 8 3 4 4 1 6 5 4 7 2 0 2 9 6 9 0 2 5 0 4
 0 3 0 2 9 4 3 7 7 1 9 6 8 4 3 4 5 4 9 3 0 8 0 5 9 1 8 1 0 0 1 5 9 1 6 8 8
 9 7 5 5 9 0 2 6 3 9 3 7 3 5 4 5 1 3 7 3 1 6 0 4 7 8]
D_sums: [4.59275796 5.32476831 3.74961727 6.37907421 4.39863821 6.32030516
 4.67477608 2.9778763  4.10763573 3.81073609]
D_counts: [11 12 10 13 10 10  7  8  8 11]
D_means: [0.41752345 0.44373069 0.37496173 0.49069802 0.43986382 0.63203052
 0.66782515 0.37223454 0.51345447 0.34643055]
0    0.417523
1    0.443731
2    0.374962
3    0.490698
4    0.439864
5    0.632031
6    0.667825
7    0.372235
8    0.513454
9    0.346431
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [80]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.29344979, 1.81004875, 0.76596413, 1.46029211, 0.98266348])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\]

In [81]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [82]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
sol1 = A * B.reshape(5,5,1)
sol2 = A * B[:,:,None]

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [83]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [84]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
print("faces:{0}\n".format(faces))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
print("F:{0}\n".format(F))
F = F.reshape(len(F)*3,2)
print("F reshape:{0}\n".format(F))
F = np.sort(F,axis=1)
print("F reshape sort:{0}\n".format(F))
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

faces:[[13 51 29]
 [54 52 10]
 [76 14 64]
 [84 19 43]
 [ 8 97 74]
 [ 9 47  0]
 [26 28 77]
 [20 83 93]
 [ 8 80 41]
 [27 15 28]]

F:[[13 51 51 29 29 13]
 [54 52 52 10 10 54]
 [76 14 14 64 64 76]
 [84 19 19 43 43 84]
 [ 8 97 97 74 74  8]
 [ 9 47 47  0  0  9]
 [26 28 28 77 77 26]
 [20 83 83 93 93 20]
 [ 8 80 80 41 41  8]
 [27 15 15 28 28 27]]

F reshape:[[13 51]
 [51 29]
 [29 13]
 [54 52]
 [52 10]
 [10 54]
 [76 14]
 [14 64]
 [64 76]
 [84 19]
 [19 43]
 [43 84]
 [ 8 97]
 [97 74]
 [74  8]
 [ 9 47]
 [47  0]
 [ 0  9]
 [26 28]
 [28 77]
 [77 26]
 [20 83]
 [83 93]
 [93 20]
 [ 8 80]
 [80 41]
 [41  8]
 [27 15]
 [15 28]
 [28 27]]

F reshape sort:[[13 51]
 [29 51]
 [13 29]
 [52 54]
 [10 52]
 [10 54]
 [14 76]
 [14 64]
 [64 76]
 [19 84]
 [19 43]
 [43 84]
 [ 8 97]
 [74 97]
 [ 8 74]
 [ 9 47]
 [ 0 47]
 [ 0  9]
 [26 28]
 [28 77]
 [26 77]
 [20 83]
 [83 93]
 [20 93]
 [ 8 80]
 [41 80]
 [ 8 41]
 [15 27]
 [15 28]
 [27 28]]

[( 0,  9) ( 0, 47) ( 8, 41) ( 8, 74) ( 8, 80) ( 8, 97) ( 9, 47) (10, 52)
 (10, 54) (13, 2

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [85]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
print("C:", C)
A = np.repeat(np.arange(len(C)), C)
print("A:", A)

C: [0 2 1 1 2 0 1]
A: [1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [87]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    print("a:", a)
    ret = np.cumsum(a, dtype=float)
    print("ret:", ret)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print("moving_average:", moving_average(Z, n=3))

a: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
ret: [  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
moving_average: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [88]:
??stride_tricks

Object `stride_tricks` not found.


In [89]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    print(shape)
    strides = (a.itemsize, a.itemsize)
    print(strides)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
input_arr = np.arange(10)
Z = rolling(np.arange(10), 3)
print(Z)

(8, 3)
(8, 8)
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [96]:
# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
print("Z=", Z)
np.logical_not(Z, out=Z)
print("Z=", Z)
Z = np.random.uniform(-1.0,1.0,100)
print("Z=", Z)
np.negative(Z, out=Z)
print("Z=", Z)

Z= [0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 1 0 1 1 1 0
 1 1 0 1 1 0 1 0 1 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 1 1]
Z= [1 1 1 1 0 1 0 1 1 1 1 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 1
 1 0 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 1 0 1 0 0 0 1
 0 0 1 0 0 1 0 1 0 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0]
Z= [-0.45232117 -0.74119557  0.90992489 -0.6105371   0.71508749 -0.79757936
  0.55358797 -0.86665148  0.23202028  0.27241439  0.71636731  0.38739109
  0.35249759  0.84758329  0.87128816  0.96606449  0.1716789   0.00199765
  0.92899447  0.93261619  0.76960547 -0.16419799 -0.25796415  0.33702622
 -0.61422679 -0.61432506 -0.89936095 -0.59048693 -0.00266073 -0.67363888
 -0.90488327  0.65674181  0.85411663 -0.33856839  0.96869051  0.33252925
  0.26462606  0.6465817  -0.5284802  -0.24156597 -0.59823001  0.39378287
 -0.72266425  0.67508613  0.51147499 -0.97676103 -0.38676354  0.53038114

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)