# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [73]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [74]:
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/rockroku/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/rockroku/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/rockroku/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/rockroku/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [75]:
zero_3 = np.zeros(10)
zero_3

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [76]:
print(zero_3.size)
print(zero_3.itemsize)


10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [77]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [78]:
temp6 = np.zeros(10)
temp6[4] = 1
temp6

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [79]:
temp7 = np.arange(10, 49)

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [80]:
temp7[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [81]:
temp9 = np.arange(0, 9)
temp9.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [82]:
temp10 = np.array([1,2,0,0,4,0])
np.nonzero(temp10)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [83]:
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [84]:
np.random.random((3, 3, 3))

array([[[ 0.26089585,  0.9069148 ,  0.87014684],
        [ 0.90914366,  0.18582104,  0.06966776],
        [ 0.64135218,  0.96960656,  0.14090351]],

       [[ 0.76794551,  0.01797268,  0.43460292],
        [ 0.19768671,  0.36874001,  0.70731659],
        [ 0.32245085,  0.92560938,  0.96696529]],

       [[ 0.65136614,  0.29471707,  0.55043754],
        [ 0.48041103,  0.16002159,  0.1963684 ],
        [ 0.89242371,  0.92650491,  0.79538165]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [85]:
temp13 = np.random.random((10, 10))
print(temp13)
print("min:", np.min(temp13))
print("max:", np.max(temp13))

[[ 0.57889966  0.91250283  0.78517243  0.025646    0.73861273  0.1782145
   0.96149191  0.91971778  0.75926797  0.57865815]
 [ 0.03109535  0.21713001  0.17915438  0.68333749  0.65408325  0.94170376
   0.83633225  0.46256164  0.25917528  0.482407  ]
 [ 0.58297427  0.60249062  0.76901543  0.60627136  0.25157761  0.41690846
   0.86837032  0.92940568  0.87745618  0.22438792]
 [ 0.56068086  0.20357348  0.57578332  0.77538184  0.05336779  0.15901602
   0.26701635  0.05669609  0.49402154  0.41523776]
 [ 0.69976397  0.47196396  0.01707108  0.28677782  0.32665609  0.23246259
   0.05080243  0.0588441   0.42954252  0.32522498]
 [ 0.35552356  0.85554515  0.60675367  0.2225742   0.1632332   0.26614603
   0.78129147  0.92271279  0.73885994  0.20802153]
 [ 0.40487291  0.80597134  0.3366792   0.12504873  0.13502638  0.85658053
   0.12555313  0.50696612  0.99855593  0.11741214]
 [ 0.45059777  0.03510283  0.36584943  0.89630234  0.39646345  0.09122453
   0.76483874  0.92971694  0.48830025  0.34266894]
 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [86]:
temp14 = np.random.random((30))
print(temp14)
print("mean:", np.mean(temp14))

[ 0.30439407  0.62101581  0.48656514  0.17839749  0.57584084  0.41328149
  0.44497799  0.4908378   0.03695806  0.69807224  0.5982367   0.32426793
  0.31697659  0.2077008   0.51597841  0.01365638  0.53010474  0.99879606
  0.69441828  0.71057347  0.17111304  0.83770627  0.32588537  0.91415696
  0.52968195  0.67166365  0.60612492  0.99348288  0.71689254  0.01064445]
mean: 0.497946744455


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [87]:
temp15 = np.ones((5, 5))
temp15[1:-1, 1:-1] = 0
temp15

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [88]:
temp16 = np.ones((5, 5))
print(temp16)
print(np.pad(temp16, 1, mode='constant'))

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [89]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
False
nan
False


In [90]:
3*0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [91]:
temp18 = np.diag([1,2,3,4], k=-1)
print(temp18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [92]:
temp19 = np.zeros((8,8))
print(temp19, end="\n\n")
temp19[1::2,::2] = 1
print(temp19, end="\n\n")
temp19[::2,1::2] = 1
print(temp19)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [93]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [94]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [95]:
temp22 = np.random.random((5,5)) * 100
print(temp22)
temp22_min = temp22.min()
temp22_max = temp22.max()
temp22_normal = (temp22-temp22_min) / (temp22_max-temp22_min)
temp22_normal

[[  6.46331852e+01   7.59833030e+01   6.95475282e+01   9.79210499e+01
    7.62315401e+01]
 [  2.27353012e+01   5.30352920e+01   9.27492489e+01   4.89977608e+01
    1.54642050e+01]
 [  1.96063317e+01   2.50453527e+01   6.18316026e+01   3.94459565e+01
    7.56810929e+00]
 [  5.85921655e+00   5.48162755e+01   3.06431633e+01   7.62007583e+01
    3.90021290e+01]
 [  3.40802817e+01   9.56018550e+01   8.12509815e-02   4.66383478e+01
    9.16669001e+01]]


array([[ 0.65977174,  0.77577891,  0.7100002 ,  1.        ,  0.77831608],
       [ 0.23154228,  0.54123211,  0.94714011,  0.49996536,  0.15722594],
       [ 0.19956174,  0.25515283,  0.63113735,  0.40233837,  0.0765216 ],
       [ 0.05905537,  0.55943517,  0.31236688,  0.77800147,  0.39780211],
       [ 0.34749694,  0.976296  ,  0.        ,  0.47585029,  0.93607765]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [96]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [97]:
temp24_1 = np.random.random((5, 3)) * 10
print(temp24_1, end="\n\n")
temp24_2 = np.random.random((3, 2)) * 10
print(temp24_2, end="\n\n")
temp24_3 = np.dot(temp24_1, temp24_2)
print(temp24_3, end="\n\n")


[[ 7.90625192  8.83040255  9.61066047]
 [ 2.35136783  2.47376782  8.97837117]
 [ 1.57791789  1.89133672  1.51599493]
 [ 5.28543726  5.8842297   4.63755405]
 [ 7.55889559  8.71981688  1.08361748]]

[[ 8.48584807  1.61256895]
 [ 6.0751574   9.41318713]
 [ 9.68703922  0.62910892]]

[[ 213.83618291  101.91776029]
 [ 121.95571276   32.72615561]
 [  39.56564204   21.30173378]
 [ 125.52320713   66.83001393]
 [ 127.61494462   94.95222183]]



#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [98]:
temp25 = np.arange(3, 9)
temp25[(3 < temp25) & (temp25 <= 8)] *= -1
temp25

array([ 3, -4, -5, -6, -7, -8])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [99]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [100]:
Z = arange(8)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [101]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9223372036854775808]
[ -9.22337204e+18]


/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  from ipykernel import kernelapp as app


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [102]:
temp29 = np.random.uniform(-10,+10,10)
print(temp29, end="\n\n")
temp29 = np.copysign(np.floor(np.abs(temp29)), temp29)
print(temp29)

[-6.76552503 -1.11735711 -4.61363841  5.4816996   6.92860279 -0.93582725
  1.01681738  1.98598729  0.17267073  3.79369957]

[-6. -1. -4.  5.  6. -0.  1.  1.  0.  3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [103]:
temp30_1 = np.arange(1, 5)
temp30_2 = np.arange(3, 6)

In [104]:
%time
print(np.intersect1d(temp30_1, temp30_2))

CPU times: user 8 µs, sys: 2 µs, total: 10 µs
Wall time: 17.9 µs
[3 4]


In [105]:
%time
print(set(temp30_1) & set(temp30_2))

CPU times: user 4 µs, sys: 2 µs, total: 6 µs
Wall time: 11.7 µs
{3, 4}


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [106]:
np.int16(32000) * np.int16(3)

/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: overflow encountered in short_scalars
  if __name__ == '__main__':


30464

In [107]:
default_setting = np.seterr()
default_setting

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [108]:
old_settings = np.seterr(all='ignore')
old_settings

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [109]:
np.int16(32000) * np.int16(3)

30464

In [110]:
old_settings = np.seterr(**default_setting)  #seterr to known value
np.int16(32000) * np.int16(3)

/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in short_scalars
  from ipykernel import kernelapp as app


30464

In [111]:
with np.errstate(over='ignore'):
    np.int16(32000) * np.int16(3)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [112]:
print("np.sqrt(-1):", np.sqrt(-1))
print("np.emath.sqrt(-1):", np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

np.sqrt(-1): nan
np.emath.sqrt(-1): 1j


/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':
/Users/rockroku/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:3: RuntimeWarning: invalid value encountered in sqrt
  app.launch_new_instance()


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [113]:
today     = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow  = today + np.timedelta64(1, 'D')
print("today:", today)
print("yesterday:", yesterday)
print("tomorrow:", tomorrow)

today: 2018-06-11
yesterday: 2018-06-10
tomorrow: 2018-06-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [114]:
np.arange(np.datetime64('2018-07-01', 'D'), np.datetime64('2018-08-01', 'D'))

array(['2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04',
       '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08',
       '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12',
       '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16',
       '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20',
       '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24',
       '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28',
       '2018-07-29', '2018-07-30', '2018-07-31'], dtype='datetime64[D]')

In [115]:
np.arange(np.datetime64('2018-07-01', 'D'), np.datetime64('2018-07-31', 'D') + 1)

array(['2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04',
       '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08',
       '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12',
       '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16',
       '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20',
       '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24',
       '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28',
       '2018-07-29', '2018-07-30', '2018-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [116]:
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
np.add(A, B, out=B)
np.divide(-A, 2, out=A)
np.multiply(A, B)

array([[-0.1984076 , -0.23193946],
       [-0.11782202, -0.13758271]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [117]:
temp_rand_36 = np.random.rand(3) * 10
print("temp_rand_36:", temp_rand_36)
print(np.floor(temp_rand_36))
print(np.ceil(temp_rand_36))
print(temp_rand_36.astype(np.int32))
print(np.trunc(temp_rand_36))
print(temp_rand_36 - temp_rand_36 % 1)

temp_rand_36: [ 5.3325645   0.98107725  5.86755795]
[ 5.  0.  5.]
[ 6.  1.  6.]
[5 0 5]
[ 5.  0.  5.]
[ 5.  0.  5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [118]:
np.zeros((5, 5)) + np.arange(0, 5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [119]:
def get_10_num():
    for i in range(10):
        yield i
np.fromiter(get_10_num(), int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [120]:
np.linspace(0, 1, num=11, endpoint=False)[1:]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [121]:
temp40 = np.random.rand(10)
print("temp40:", temp40)
print("temp40 sorted:", np.sort(temp40))

temp40: [ 0.31606479  0.58541638  0.23897347  0.42601041  0.34593587  0.73837763
  0.60625959  0.34786654  0.08788195  0.52998995]
temp40 sorted: [ 0.08788195  0.23897347  0.31606479  0.34593587  0.34786654  0.42601041
  0.52998995  0.58541638  0.60625959  0.73837763]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [122]:
%time
temp41 = np.arange(10)
print("temp41:", temp41)
print(np.add.reduce(temp41))

CPU times: user 5 µs, sys: 2 µs, total: 7 µs
Wall time: 13.1 µs
temp41: [0 1 2 3 4 5 6 7 8 9]
45


In [123]:
%time
temp41_2 = np.arange(10)
print("temp41_2:", temp41_2)
print(np.sum(temp41_2))

CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 12.9 µs
temp41_2: [0 1 2 3 4 5 6 7 8 9]
45


In [124]:
%time
temp41_2 = np.arange(10)
print("temp41_2:", temp41_2)
print(temp41_2.sum())

CPU times: user 6 µs, sys: 2 µs, total: 8 µs
Wall time: 13.1 µs
temp41_2: [0 1 2 3 4 5 6 7 8 9]
45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [125]:
temp42_1 = [1.1, 2]
temp42_2 = [1.10001, 2]
print(np.allclose(temp42_1, temp42_2))
print(np.array_equal(temp42_1, temp42_2))

True
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [126]:
# temp43 = np.zeros(5)
# temp43.flags.writeable = False
# temp43[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [127]:
temp44 = np.random.rand(10, 2)
x,y = temp44[:,0], temp44[:,1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(x, y)
print(r)
print(theta)

[ 0.42629924  1.00715781  0.88470756  1.02115366  1.20793861  0.42261421
  0.67064425  0.80501728  0.41934315  0.26792006]
[ 0.68832116  1.41825575  0.40232358  1.10590422  0.71645922  0.69989243
  0.13803027  1.47492043  0.79855403  1.50035659]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [128]:
temp45 = np.random.rand(10)
print(temp45)
max_idx = np.argmax(temp45)
temp45[max_idx] = 0
print(temp45)

[ 0.17212618  0.22830494  0.4016244   0.11021095  0.20209739  0.88719539
  0.03127564  0.63286093  0.31513722  0.60404441]
[ 0.17212618  0.22830494  0.4016244   0.11021095  0.20209739  0.
  0.03127564  0.63286093  0.31513722  0.60404441]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [129]:
temp_46 = np.zeros((5,5), [('xx',float),('yy',float)])
temp_46['xx'], temp_46['yy'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,2,5))
temp_46

array([[( 0.  ,  0. ), ( 0.25,  0. ), ( 0.5 ,  0. ), ( 0.75,  0. ),
        ( 1.  ,  0. )],
       [( 0.  ,  0.5), ( 0.25,  0.5), ( 0.5 ,  0.5), ( 0.75,  0.5),
        ( 1.  ,  0.5)],
       [( 0.  ,  1. ), ( 0.25,  1. ), ( 0.5 ,  1. ), ( 0.75,  1. ),
        ( 1.  ,  1. )],
       [( 0.  ,  1.5), ( 0.25,  1.5), ( 0.5 ,  1.5), ( 0.75,  1.5),
        ( 1.  ,  1.5)],
       [( 0.  ,  2. ), ( 0.25,  2. ), ( 0.5 ,  2. ), ( 0.75,  2. ),
        ( 1.  ,  2. )]],
      dtype=[('xx', '<f8'), ('yy', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [130]:
X47 = np.array([1, 2, 3])
Y47 = np.array([4, 5, 6])
r47 = np.zeros((len(X47),len(Y47)))
for i in range(len(X47)):
    for j in range(len(Y47)):
        r47[i,j] = np.subtract(X47[i], Y47[j])
r47

array([[-3., -4., -5.],
       [-2., -3., -4.],
       [-1., -2., -3.]])

In [131]:
 np.subtract.outer(X47, Y47)

array([[-3, -4, -5],
       [-2, -3, -4],
       [-1, -2, -3]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [132]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype))

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype))
    print(np.finfo(dtype))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
--------------------------------------------------------------

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [133]:
np.set_printoptions(threshold=5)
Z = np.zeros((16,16))
print(Z)
np.set_printoptions(threshold=np.nan)
print(Z)

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [134]:
temp50 = [5, 1, 2, 3, 4]
val50 = 3
temp50_2 = np.abs(np.subtract(temp50,val50))
np.argmin(temp50_2)

3

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [135]:
temp51 = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(temp51)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [136]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

print("====")
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[ 0.          0.17447854  0.28798462  0.08725743  0.19675582  0.70072278
   0.62624945  0.20581218  0.3610033   0.49606697]
 [ 0.17447854  0.          0.32064538  0.10800559  0.14660712  0.6978535
   0.61903995  0.03260427  0.33877355  0.53154746]
 [ 0.28798462  0.32064538  0.          0.24706685  0.17960604  0.41305591
   0.33980281  0.34416823  0.11304812  0.21470275]
 [ 0.08725743  0.10800559  0.24706685  0.          0.11549859  0.65062105
   0.57367193  0.14045876  0.29790281  0.46168425]
 [ 0.19675582  0.14660712  0.17960604  0.11549859  0.          0.55340174
   0.47493881  0.1663906   0.19451007  0.38610851]
 [ 0.70072278  0.6978535   0.41305591  0.65062105  0.55340174  0.
   0.07904599  0.71158426  0.35918094  0.22943819]
 [ 0.62624945  0.61903995  0.33980281  0.57367193  0.47493881  0.07904599
   0.          0.632579    0.28053363  0.17721523]
 [ 0.20581218  0.03260427  0.34416823  0.14045876  0.1663906   0.71158426
   0.632579    0.          0.35364138  0.55248071]
 [ 0.3610

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [137]:
temp53 = np.arange(10, dtype=np.float32)
print(temp53)
temp53 = temp53.astype(np.int32, copy=False)
print(temp53)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [139]:
# from io import StringIO

# # Fake file 
# s = StringIO("""1, 2, 3, 4, 5\n
#                 6,  ,  , 7, 8\n
#                  ,  , 9,10,11\n""")
# print(type(s))
# Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
# print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [142]:
Z = np.arange(9).reshape(3,3)
print(Z)
for index, value in np.ndenumerate(Z):
    print(index, value)
print("==")
for index in np.ndindex(Z.shape):
    print(index, Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
==
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)